#!/usr/bin/env bash
# Installs Nginx and configures it for a 301 redirection

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Create a simple HTML file for the root page
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx to handle redirection
cat > /etc/nginx/sites-available/default << EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

# Test the Nginx configuration for syntax errors
nginx -t

# Restart Nginx to apply the changes
service nginx restart

